package com.zespolowe.server.dataFormats;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Cirben
 */
public class Point {
	String displayName;
	Coords coords;
	int id;
	ArrayList<Transport> transports;	
    Map<String, Boolean> added;
	
	public Point(int id){
		this.id = id;
	}

	public void addTransport(Transport t){
		String line = t.line;
		if(!added.containsKey(line)){
			transports.add(t);
			added.put(line, true);
		}
	}
	
	public Point(int id, String displayName, Coords coords){
		this.id = id;
		this.displayName = displayName;
		this.coords = coords;
		this.transports = new ArrayList<>();
		this.added = new HashMap();
	} 
	
	public Point(int id, String displayName, double x, double y){
		this.id = id;
		this.displayName = displayName;
		coords = new Coords(x,y);
		this.transports = new ArrayList<>();
		this.added = new HashMap();
	}

	public String getDisplayName() {
		return displayName;
	}

	public Coords getCoords() {
		return coords;
	}

	public int getId() {
		return id;
	}
	
	/* Added equals() and hashCode() that were generated by Eclipse because I need these for Delays. */
	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj)
	{
		if(this == obj) return true;
		if(obj == null) return false;
		if(getClass() != obj.getClass()) return false;
		Point other = (Point) obj;
		if(id != other.id) return false;
		return true;
	}
}
